export const fieldIds = {
  firstName: "first_name",
  lastName: "last_name",
  preferredName: "preferred_name",
  birthDate: "birth_date",
  governmentId: "government_id",
  pronouns: "pronouns",
  shirtSize: "shirt_size",
  shirtStyle: "shirt_style",
  mailingRecipient: "recipient",
  mailingStreet: "street",
  mailingExternalNumber: "external_number",
  mailingInternalNumber: "internal_number",
  mailingZipcode: "zipcode",
  mailingCountry: "mailing_country",
  mailingState: "mailing_state",
  mailingMunicipality: "mailing_municipality",
  mailingLocality: "mailing_locality",
  mailingReferences: "references",
  mailingPhone: "phone",
  schoolCountry: "school_country",
  schoolState: "school_state",
  schoolName: "school_name",
  schoolStage: "school_stage",
  schoolGrade: "school_grade",
};
